### ISSUE TITLE
Discuss what to do with availibilities which end/start at the same time

### ISSUE THREAD

**Issue by nowickamagdalena** [nowickamagdalena/book-my-look#15]
Problem is with generating slots for a salon service, because slot can be created in a scope of just one availability. So we need to decide what to do with availibilities that start/end at the same time:
- forbid creating them by employee
- merge availability during adding with ones that have same time boundaries
- ignore it, and leave it as it is, so slots will be generated only in single avaliabilty (no slot starting in one availability and finishing in the next one)

**Comment by zsikorska** [comment]
I opt for first or second option. It depends which option would be easier to implement - i think merging could be harder bc it will require checking all the availibilities of the employee. Maybe it will be easier to avoid creating availability that start/end at the same time on frontend using library for calendar (it depends on the options in that library). What's your point of view?

**Comment by nowickamagdalena** [comment]
Merging will be more difficult for sure, we can go with the first option, as it will be easy to block it on backend too, I hope the teacher will be ok with this
